ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ kronos.project.ApplicationKt.module ]
  }
}

database {
  initOnStartup = true
  url = "jdbc:postgresql://localhost:5432/hackitall"
  user = "postgres"
  password = "postgres"
  maxPoolSize = 10
}

jwt {
  secret = "change-this-jwt-secret-for-production"
  issuer = "hackitall-backend"
  audience = "hackitall-clients"
  realm = "Access to city reporter API"
  expiresInHours = 24
}

